name: Continuous deployment

on:
  push:
    branches: [main]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: benjaminarski-dist
          path: dist
          if-no-files-found: error

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: benjaminarski-dist
          path: dist

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          cname: www.benjaminarski.dev
